/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 logoPP9.glb -r public -k 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useExplode } from "hooks/useExplode";



export default function Model(props) {
  const { nodes, materials } = useGLTF('/logoPP9.glb')
  const group = useRef();

  useExplode(group, {
    distance: 6,
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh name="Text_cell" geometry={nodes.Text_cell.geometry} material={materials['Material.001']} position={[1.809, 1.193, 0.117]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell001" geometry={nodes.Text_cell001.geometry} material={materials['Material.001']} position={[1.869, 0.067, 0.049]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell002" geometry={nodes.Text_cell002.geometry} material={materials['Material.001']} position={[1.546, 1.052, 0.116]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell003" geometry={nodes.Text_cell003.geometry} material={materials['Material.001']} position={[1.522, -0.2, 0.13]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell004" geometry={nodes.Text_cell004.geometry} material={materials['Material.001']} position={[1.716, -0.747, 0.114]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell005" geometry={nodes.Text_cell005.geometry} material={materials['Material.001']} position={[1.822, 0.166, 0.105]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell006" geometry={nodes.Text_cell006.geometry} material={materials['Material.001']} position={[0.457, 0.432, -0.112]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell007" geometry={nodes.Text_cell007.geometry} material={materials['Material.001']} position={[1.236, 1.037, 0.142]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell008" geometry={nodes.Text_cell008.geometry} material={materials['Material.001']} position={[1.224, -0.253, 0.11]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell009" geometry={nodes.Text_cell009.geometry} material={materials['Material.001']} position={[0.468, -0.091, -0.107]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell010" geometry={nodes.Text_cell010.geometry} material={materials['Material.001']} position={[1.808, -1.379, 0.064]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell011" geometry={nodes.Text_cell011.geometry} material={materials['Material.001']} position={[0.485, 0.87, -0.12]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell012" geometry={nodes.Text_cell012.geometry} material={materials['Material.001']} position={[0.275, 0.055, -0.004]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell013" geometry={nodes.Text_cell013.geometry} material={materials['Material.001']} position={[1.837, -1.272, -0.112]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell014" geometry={nodes.Text_cell014.geometry} material={materials['Material.001']} position={[1.885, 0.373, -0.045]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell015" geometry={nodes.Text_cell015.geometry} material={materials['Material.001']} position={[1.178, -0.147, -0.129]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell016" geometry={nodes.Text_cell016.geometry} material={materials['Material.001']} position={[0.368, 0.23, 0.165]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell017" geometry={nodes.Text_cell017.geometry} material={materials['Material.001']} position={[1.377, 0.201, 0.137]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell018" geometry={nodes.Text_cell018.geometry} material={materials['Material.001']} position={[1.238, 0.231, -0.089]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell019" geometry={nodes.Text_cell019.geometry} material={materials['Material.001']} position={[0.688, -0.179, -0.065]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell020" geometry={nodes.Text_cell020.geometry} material={materials['Material.001']} position={[1.872, 0.682, -0.035]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell021" geometry={nodes.Text_cell021.geometry} material={materials['Material.001']} position={[1.892, -0.14, -0.074]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell022" geometry={nodes.Text_cell022.geometry} material={materials['Material.001']} position={[0.903, 0.931, 0.022]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell023" geometry={nodes.Text_cell023.geometry} material={materials['Material.001']} position={[0.294, 1.118, 0.109]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell024" geometry={nodes.Text_cell024.geometry} material={materials['Material.001']} position={[1.624, -1.082, -0.085]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell025" geometry={nodes.Text_cell025.geometry} material={materials['Material.001']} position={[1.269, 1.083, -0.124]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell026" geometry={nodes.Text_cell026.geometry} material={materials['Material.001']} position={[0.208, 0.918, 0.109]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell027" geometry={nodes.Text_cell027.geometry} material={materials['Material.001']} position={[0.973, 0.978, -0.07]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell028" geometry={nodes.Text_cell028.geometry} material={materials['Material.001']} position={[0.208, 1.009, -0.041]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell029" geometry={nodes.Text_cell029.geometry} material={materials['Material.001']} position={[1.34, 0.808, 0.076]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell030" geometry={nodes.Text_cell030.geometry} material={materials['Material.001']} position={[0.155, 0.401, 0.03]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell031" geometry={nodes.Text_cell031.geometry} material={materials['Material.001']} position={[1.71, 0.374, -0.113]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell032" geometry={nodes.Text_cell032.geometry} material={materials['Material.001']} position={[1.785, -1.166, 0.132]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell033" geometry={nodes.Text_cell033.geometry} material={materials['Material.001']} position={[1.63, -1.35, -0.123]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell034" geometry={nodes.Text_cell034.geometry} material={materials['Material.001']} position={[1.829, -0.661, -0.091]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell035" geometry={nodes.Text_cell035.geometry} material={materials['Material.001']} position={[1.59, 0.298, 0.114]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell036" geometry={nodes.Text_cell036.geometry} material={materials['Material.001']} position={[1.68, 0.609, -0.111]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell037" geometry={nodes.Text_cell037.geometry} material={materials['Material.001']} position={[1.469, -0.938, 0.02]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell038" geometry={nodes.Text_cell038.geometry} material={materials['Material.001']} position={[1.481, -1.384, 0.049]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell039" geometry={nodes.Text_cell039.geometry} material={materials['Material.001']} position={[0.961, -0.205, 0.005]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell040" geometry={nodes.Text_cell040.geometry} material={materials['Material.001']} position={[1.75, -0.118, -0.112]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell041" geometry={nodes.Text_cell041.geometry} material={materials['Material.001']} position={[0.379, 1.23, -0.057]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell042" geometry={nodes.Text_cell042.geometry} material={materials['Material.001']} position={[1.795, 1.405, 0.002]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell043" geometry={nodes.Text_cell043.geometry} material={materials['Material.001']} position={[1.253, -0.044, 0.127]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell044" geometry={nodes.Text_cell044.geometry} material={materials['Material.001']} position={[0.576, -0.107, 0.103]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell045" geometry={nodes.Text_cell045.geometry} material={materials['Material.001']} position={[0.7, 1.326, 0.132]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell046" geometry={nodes.Text_cell046.geometry} material={materials['Material.001']} position={[1.649, -0.843, -0.129]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell047" geometry={nodes.Text_cell047.geometry} material={materials['Material.001']} position={[0.863, 1.203, -0.149]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell048" geometry={nodes.Text_cell048.geometry} material={materials['Material.001']} position={[1.119, 1.027, -0.094]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell049" geometry={nodes.Text_cell049.geometry} material={materials['Material.001']} position={[1.89, 0.805, 0.063]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell050" geometry={nodes.Text_cell050.geometry} material={materials['Material.001']} position={[0.433, 1.058, 0.133]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell051" geometry={nodes.Text_cell051.geometry} material={materials['Material.001']} position={[1.896, 1.324, -0.053]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell052" geometry={nodes.Text_cell052.geometry} material={materials['Material.001']} position={[1.823, -0.083, 0.099]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell053" geometry={nodes.Text_cell053.geometry} material={materials['Material.001']} position={[1.108, 1.348, -0.117]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell054" geometry={nodes.Text_cell054.geometry} material={materials['Material.001']} position={[0.705, 1.368, -0.054]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell055" geometry={nodes.Text_cell055.geometry} material={materials['Material.001']} position={[1.657, 0.555, 0.136]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell056" geometry={nodes.Text_cell056.geometry} material={materials['Material.001']} position={[1.386, 0.396, 0.034]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell057" geometry={nodes.Text_cell057.geometry} material={materials['Material.001']} position={[0.182, 0.754, 0.067]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell058" geometry={nodes.Text_cell058.geometry} material={materials['Material.001']} position={[1.536, -1.261, 0.117]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell059" geometry={nodes.Text_cell059.geometry} material={materials['Material.001']} position={[1.464, -0.127, -0.133]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell060" geometry={nodes.Text_cell060.geometry} material={materials['Material.001']} position={[0.659, 0.712, -0.064]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell061" geometry={nodes.Text_cell061.geometry} material={materials['Material.001']} position={[0.49, 1.153, -0.14]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell062" geometry={nodes.Text_cell062.geometry} material={materials['Material.001']} position={[1.828, 0.404, 0.128]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell063" geometry={nodes.Text_cell063.geometry} material={materials['Material.001']} position={[1.73, 1.287, -0.131]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell064" geometry={nodes.Text_cell064.geometry} material={materials['Material.001']} position={[1.448, 0.553, -0.114]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell065" geometry={nodes.Text_cell065.geometry} material={materials['Material.001']} position={[1.357, 1.392, 0.064]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell066" geometry={nodes.Text_cell066.geometry} material={materials['Material.001']} position={[1.46, -1.358, -0.094]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell067" geometry={nodes.Text_cell067.geometry} material={materials['Material.001']} position={[1.799, -0.355, 0.098]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell068" geometry={nodes.Text_cell068.geometry} material={materials['Material.001']} position={[0.686, 0.084, -0.152]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell069" geometry={nodes.Text_cell069.geometry} material={materials['Material.001']} position={[0.682, 0.969, -0.133]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell070" geometry={nodes.Text_cell070.geometry} material={materials['Material.001']} position={[0.639, 0.76, 0.132]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell071" geometry={nodes.Text_cell071.geometry} material={materials['Material.001']} position={[0.608, 0.837, -0.158]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell072" geometry={nodes.Text_cell072.geometry} material={materials['Material.001']} position={[1.867, -0.974, -0.054]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell073" geometry={nodes.Text_cell073.geometry} material={materials['Material.001']} position={[0.578, 0.274, 0.141]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell074" geometry={nodes.Text_cell074.geometry} material={materials['Material.001']} position={[0.765, 0.297, 0.051]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell075" geometry={nodes.Text_cell075.geometry} material={materials['Material.001']} position={[1.059, 1.304, 0.116]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell076" geometry={nodes.Text_cell076.geometry} material={materials['Material.001']} position={[1.614, 0.898, -0.127]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell077" geometry={nodes.Text_cell077.geometry} material={materials['Material.001']} position={[0.47, 1.27, 0.071]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell078" geometry={nodes.Text_cell078.geometry} material={materials['Material.001']} position={[1.014, 0.179, -0.043]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell079" geometry={nodes.Text_cell079.geometry} material={materials['Material.001']} position={[1.734, 0.795, 0.116]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell080" geometry={nodes.Text_cell080.geometry} material={materials['Material.001']} position={[0.509, 0.041, -0.125]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell081" geometry={nodes.Text_cell081.geometry} material={materials['Material.001']} position={[1.354, 1.203, 0.079]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell082" geometry={nodes.Text_cell082.geometry} material={materials['Material.001']} position={[1.417, -1.089, -0.013]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell083" geometry={nodes.Text_cell083.geometry} material={materials['Material.001']} position={[1.432, -0.594, 0.085]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell084" geometry={nodes.Text_cell084.geometry} material={materials['Material.001']} position={[1.525, -0.675, -0.131]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell085" geometry={nodes.Text_cell085.geometry} material={materials['Material.001']} position={[1.347, 0.931, -0.105]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell086" geometry={nodes.Text_cell086.geometry} material={materials['Material.001']} position={[1.449, -1.182, -0.096]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell087" geometry={nodes.Text_cell087.geometry} material={materials['Material.001']} position={[0.763, -0.087, -0.15]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell088" geometry={nodes.Text_cell088.geometry} material={materials['Material.001']} position={[1.827, 1.057, -0.1]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell089" geometry={nodes.Text_cell089.geometry} material={materials['Material.001']} position={[1.759, -0.334, -0.113]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell090" geometry={nodes.Text_cell090.geometry} material={materials['Material.001']} position={[1.657, 1.352, 0.111]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell091" geometry={nodes.Text_cell091.geometry} material={materials['Material.001']} position={[1.708, 0.085, -0.1]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell092" geometry={nodes.Text_cell092.geometry} material={materials['Material.001']} position={[0.321, 0.745, -0.143]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell093" geometry={nodes.Text_cell093.geometry} material={materials['Material.001']} position={[1.452, -0.41, -0.08]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell094" geometry={nodes.Text_cell094.geometry} material={materials['Material.001']} position={[0.939, 0.015, 0.138]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell095" geometry={nodes.Text_cell095.geometry} material={materials['Material.001']} position={[1.498, 1.277, -0.096]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell096" geometry={nodes.Text_cell096.geometry} material={materials['Material.001']} position={[0.761, 0.114, 0.13]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell097" geometry={nodes.Text_cell097.geometry} material={materials['Material.001']} position={[1.36, 0.194, -0.154]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell098" geometry={nodes.Text_cell098.geometry} material={materials['Material.001']} position={[0.805, 1.093, 0.144]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text_cell099" geometry={nodes.Text_cell099.geometry} material={materials['Material.001']} position={[0.29, 0.155, -0.139]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell" geometry={nodes.Text001_cell.geometry} material={materials['Material.002']} position={[-0.873, 1.322, -0.137]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell001" geometry={nodes.Text001_cell001.geometry} material={materials['Material.002']} position={[-0.411, 0.063, -0.133]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell002" geometry={nodes.Text001_cell002.geometry} material={materials['Material.002']} position={[-1.658, -0.999, -0.073]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell003" geometry={nodes.Text001_cell003.geometry} material={materials['Material.002']} position={[-1.73, 1.16, 0.119]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell004" geometry={nodes.Text001_cell004.geometry} material={materials['Material.002']} position={[-1.696, -1.302, 0.13]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell005" geometry={nodes.Text001_cell005.geometry} material={materials['Material.002']} position={[-1.538, -0.364, 0.134]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell006" geometry={nodes.Text001_cell006.geometry} material={materials['Material.002']} position={[-1.381, -0.225, 0.137]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell007" geometry={nodes.Text001_cell007.geometry} material={materials['Material.002']} position={[-1.858, -1.214, 0.098]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell008" geometry={nodes.Text001_cell008.geometry} material={materials['Material.002']} position={[-0.808, 1.087, 0.147]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell009" geometry={nodes.Text001_cell009.geometry} material={materials['Material.002']} position={[-0.145, 0.576, 0.014]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell010" geometry={nodes.Text001_cell010.geometry} material={materials['Material.002']} position={[-0.866, 0.041, 0.124]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell011" geometry={nodes.Text001_cell011.geometry} material={materials['Material.002']} position={[-0.382, 0.441, -0.141]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell012" geometry={nodes.Text001_cell012.geometry} material={materials['Material.002']} position={[-1.755, -1.082, -0.098]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell013" geometry={nodes.Text001_cell013.geometry} material={materials['Material.002']} position={[-1.494, -0.445, -0.11]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell014" geometry={nodes.Text001_cell014.geometry} material={materials['Material.002']} position={[-0.946, -0.119, -0.106]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell015" geometry={nodes.Text001_cell015.geometry} material={materials['Material.002']} position={[-0.203, 0.179, -0.103]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell016" geometry={nodes.Text001_cell016.geometry} material={materials['Material.002']} position={[-1.774, -0.552, -0.109]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell017" geometry={nodes.Text001_cell017.geometry} material={materials['Material.002']} position={[-1.483, 0.926, 0.137]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell018" geometry={nodes.Text001_cell018.geometry} material={materials['Material.002']} position={[-1.669, 0.334, -0.141]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell019" geometry={nodes.Text001_cell019.geometry} material={materials['Material.002']} position={[-1.255, 1.204, -0.155]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell020" geometry={nodes.Text001_cell020.geometry} material={materials['Material.002']} position={[-1.056, -0.214, 0.103]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell021" geometry={nodes.Text001_cell021.geometry} material={materials['Material.002']} position={[-1.625, 1.298, -0.128]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell022" geometry={nodes.Text001_cell022.geometry} material={materials['Material.002']} position={[-1.76, -1.253, -0.144]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell023" geometry={nodes.Text001_cell023.geometry} material={materials['Material.002']} position={[-1.564, -0.765, 0.101]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell024" geometry={nodes.Text001_cell024.geometry} material={materials['Material.002']} position={[-1.024, 1.234, 0.142]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell025" geometry={nodes.Text001_cell025.geometry} material={materials['Material.002']} position={[-1.817, 0.167, 0.058]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell026" geometry={nodes.Text001_cell026.geometry} material={materials['Material.002']} position={[-0.319, 0.067, 0.073]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell027" geometry={nodes.Text001_cell027.geometry} material={materials['Material.002']} position={[-0.538, 0.422, 0.101]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell028" geometry={nodes.Text001_cell028.geometry} material={materials['Material.002']} position={[-1.131, -0.173, -0.105]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell029" geometry={nodes.Text001_cell029.geometry} material={materials['Material.002']} position={[-1.895, -0.289, 0.085]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell030" geometry={nodes.Text001_cell030.geometry} material={materials['Material.002']} position={[-1.881, 1.248, -0.043]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell031" geometry={nodes.Text001_cell031.geometry} material={materials['Material.002']} position={[-0.158, 0.273, 0.011]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell032" geometry={nodes.Text001_cell032.geometry} material={materials['Material.002']} position={[-1.224, 0.235, 0.025]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell033" geometry={nodes.Text001_cell033.geometry} material={materials['Material.002']} position={[-0.619, 1.332, -0.066]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell034" geometry={nodes.Text001_cell034.geometry} material={materials['Material.002']} position={[-0.779, -0.17, -0.13]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell035" geometry={nodes.Text001_cell035.geometry} material={materials['Material.002']} position={[-1.192, 0.139, -0.146]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell036" geometry={nodes.Text001_cell036.geometry} material={materials['Material.002']} position={[-0.616, -0.161, -0.024]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell037" geometry={nodes.Text001_cell037.geometry} material={materials['Material.002']} position={[-1.907, 0.654, 0.011]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell038" geometry={nodes.Text001_cell038.geometry} material={materials['Material.002']} position={[-1.678, 0.758, 0.119]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell039" geometry={nodes.Text001_cell039.geometry} material={materials['Material.002']} position={[-0.201, 0.917, 0.016]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell040" geometry={nodes.Text001_cell040.geometry} material={materials['Material.002']} position={[-1.738, -0.337, 0.092]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell041" geometry={nodes.Text001_cell041.geometry} material={materials['Material.002']} position={[-1.875, -0.437, -0.062]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell042" geometry={nodes.Text001_cell042.geometry} material={materials['Material.002']} position={[-1.586, 0.382, 0.133]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell043" geometry={nodes.Text001_cell043.geometry} material={materials['Material.002']} position={[-1.805, -0.756, -0.102]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell044" geometry={nodes.Text001_cell044.geometry} material={materials['Material.002']} position={[-1.461, -1.106, -0.003]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell045" geometry={nodes.Text001_cell045.geometry} material={materials['Material.002']} position={[-1.472, 1.138, 0.092]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell046" geometry={nodes.Text001_cell046.geometry} material={materials['Material.002']} position={[-1.476, -0.81, -0.082]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell047" geometry={nodes.Text001_cell047.geometry} material={materials['Material.002']} position={[-1.335, 0.846, 0.14]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell048" geometry={nodes.Text001_cell048.geometry} material={materials['Material.002']} position={[-0.818, -0.183, 0.115]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell049" geometry={nodes.Text001_cell049.geometry} material={materials['Material.002']} position={[-1.86, 0.961, 0.102]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell050" geometry={nodes.Text001_cell050.geometry} material={materials['Material.002']} position={[-1.801, 1.374, 0.088]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell051" geometry={nodes.Text001_cell051.geometry} material={materials['Material.002']} position={[-1.871, -0.694, 0.095]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell052" geometry={nodes.Text001_cell052.geometry} material={materials['Material.002']} position={[-0.621, 0.191, -0.145]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell053" geometry={nodes.Text001_cell053.geometry} material={materials['Material.002']} position={[-1.799, -0.528, 0.096]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell054" geometry={nodes.Text001_cell054.geometry} material={materials['Material.002']} position={[-1.64, 1.011, 0.108]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell055" geometry={nodes.Text001_cell055.geometry} material={materials['Material.002']} position={[-0.769, 0.835, -0.025]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell056" geometry={nodes.Text001_cell056.geometry} material={materials['Material.002']} position={[-1.469, 1.379, 0.027]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell057" geometry={nodes.Text001_cell057.geometry} material={materials['Material.002']} position={[-0.73, 1.114, -0.145]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell058" geometry={nodes.Text001_cell058.geometry} material={materials['Material.002']} position={[-1.744, -0.941, 0.116]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell059" geometry={nodes.Text001_cell059.geometry} material={materials['Material.002']} position={[-1.849, 0.382, 0.087]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell060" geometry={nodes.Text001_cell060.geometry} material={materials['Material.002']} position={[-0.439, 1.213, -0.007]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell061" geometry={nodes.Text001_cell061.geometry} material={materials['Material.002']} position={[-1.443, 0.48, 0.118]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell062" geometry={nodes.Text001_cell062.geometry} material={materials['Material.002']} position={[-1.504, -0.452, 0.129]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell063" geometry={nodes.Text001_cell063.geometry} material={materials['Material.002']} position={[-1.748, 0.925, -0.104]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell064" geometry={nodes.Text001_cell064.geometry} material={materials['Material.002']} position={[-1.434, 0.823, -0.129]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell065" geometry={nodes.Text001_cell065.geometry} material={materials['Material.002']} position={[-1.331, 1.353, 0.08]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell066" geometry={nodes.Text001_cell066.geometry} material={materials['Material.002']} position={[-1.572, -0.194, -0.131]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell067" geometry={nodes.Text001_cell067.geometry} material={materials['Material.002']} position={[-1.903, -1.063, -0.096]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell068" geometry={nodes.Text001_cell068.geometry} material={materials['Material.002']} position={[-1.162, 1.412, -0.057]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell069" geometry={nodes.Text001_cell069.geometry} material={materials['Material.002']} position={[-1.853, -0.998, 0.072]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell070" geometry={nodes.Text001_cell070.geometry} material={materials['Material.002']} position={[-1.88, -1.372, -0.052]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell071" geometry={nodes.Text001_cell071.geometry} material={materials['Material.002']} position={[-0.454, 1.028, 0.15]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell072" geometry={nodes.Text001_cell072.geometry} material={materials['Material.002']} position={[-0.755, 1.371, 0.042]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell073" geometry={nodes.Text001_cell073.geometry} material={materials['Material.002']} position={[-0.518, 0.755, 0.138]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell074" geometry={nodes.Text001_cell074.geometry} material={materials['Material.002']} position={[-0.236, 0.803, -0.147]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell075" geometry={nodes.Text001_cell075.geometry} material={materials['Material.002']} position={[-1.415, -0.556, 0.086]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell076" geometry={nodes.Text001_cell076.geometry} material={materials['Material.002']} position={[-1.266, 1.073, 0.143]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell077" geometry={nodes.Text001_cell077.geometry} material={materials['Material.002']} position={[-1.077, -0.034, 0.146]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell078" geometry={nodes.Text001_cell078.geometry} material={materials['Material.002']} position={[-1.899, -1.19, -0.043]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell079" geometry={nodes.Text001_cell079.geometry} material={materials['Material.002']} position={[-0.817, 0.271, 0.029]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell080" geometry={nodes.Text001_cell080.geometry} material={materials['Material.002']} position={[-1.528, -1.37, -0.005]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell081" geometry={nodes.Text001_cell081.geometry} material={materials['Material.002']} position={[-0.552, 0.876, -0.151]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell082" geometry={nodes.Text001_cell082.geometry} material={materials['Material.002']} position={[-1.736, 0.582, 0.141]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell083" geometry={nodes.Text001_cell083.geometry} material={materials['Material.002']} position={[-1.872, -0.907, -0.092]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell084" geometry={nodes.Text001_cell084.geometry} material={materials['Material.002']} position={[-1.06, 1.022, -0.116]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell085" geometry={nodes.Text001_cell085.geometry} material={materials['Material.002']} position={[-1.711, 1.274, 0.156]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell086" geometry={nodes.Text001_cell086.geometry} material={materials['Material.002']} position={[-1.846, -0.064, -0.095]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell087" geometry={nodes.Text001_cell087.geometry} material={materials['Material.002']} position={[-1.332, -0.327, -0.047]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell088" geometry={nodes.Text001_cell088.geometry} material={materials['Material.002']} position={[-0.276, 0.244, -0.141]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell089" geometry={nodes.Text001_cell089.geometry} material={materials['Material.002']} position={[-0.812, 0.089, -0.121]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell090" geometry={nodes.Text001_cell090.geometry} material={materials['Material.002']} position={[-0.659, -0.057, -0.137]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell091" geometry={nodes.Text001_cell091.geometry} material={materials['Material.002']} position={[-1.299, 0.858, 0]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell092" geometry={nodes.Text001_cell092.geometry} material={materials['Material.002']} position={[-1.5, -0.6, -0.09]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell093" geometry={nodes.Text001_cell093.geometry} material={materials['Material.002']} position={[-1.435, 0.139, 0.125]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell094" geometry={nodes.Text001_cell094.geometry} material={materials['Material.002']} position={[-1.788, -0.071, 0.109]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell095" geometry={nodes.Text001_cell095.geometry} material={materials['Material.002']} position={[-0.525, 0.678, -0.111]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell096" geometry={nodes.Text001_cell096.geometry} material={materials['Material.002']} position={[-1.42, 0.356, -0.107]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell097" geometry={nodes.Text001_cell097.geometry} material={materials['Material.002']} position={[-0.181, 0.399, 0.14]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell098" geometry={nodes.Text001_cell098.geometry} material={materials['Material.002']} position={[-0.557, -0.043, 0.118]} rotation={[-Math.PI, 0, 0]} scale={-1} />
      <mesh name="Text001_cell099" geometry={nodes.Text001_cell099.geometry} material={materials['Material.002']} position={[-1.349, -0.07, -0.131]} rotation={[-Math.PI, 0, 0]} scale={-1} />
    </group>
  )
}

useGLTF.preload('/../logoPP9.glb')
